name: Czolish, newbie
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  portfolio:
    output: false
    permalink: /portfolio/:path/
